name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: kolosys/.actions/.github/workflows/release-workflow.yml@main
    with:
      repository_name: "ion"
      go_version: "1.22"
    secrets:
      app_id: ${{ vars.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
